-- =============================================================
-- Dados de seed para desenvolvimento
-- Execute APÓS criar o schema e APÓS criar um usuário admin no Auth
-- =============================================================
-- ATENÇÃO: Este arquivo é apenas para desenvolvimento.
-- NÃO execute em produção.

-- Inserir alunos de exemplo
insert into public.students (id, full_name, preferred_name, email, phone, company, job_title, industry, company_size, city, state, years_experience) values
  ('a1000000-0000-0000-0000-000000000001', 'Ana Carolina Ferreira', 'Ana', 'ana.ferreira@exemplo.com', '(11) 99999-0001', 'TechCorp Brasil', 'Diretora de Operações', 'Tecnologia', '201-500', 'São Paulo', 'SP', '10-15 anos'),
  ('a1000000-0000-0000-0000-000000000002', 'Bruno Oliveira Santos', 'Bruno', 'bruno.santos@exemplo.com', '(21) 99999-0002', 'Varejo Max', 'Gerente Comercial', 'Varejo', '51-200', 'Rio de Janeiro', 'RJ', '5-10 anos'),
  ('a1000000-0000-0000-0000-000000000003', 'Carla Mendes Lima', 'Carla', 'carla.lima@exemplo.com', '(31) 99999-0003', 'HealthPlus', 'Head de RH', 'Saúde', '501-1000', 'Belo Horizonte', 'MG', '8-12 anos'),
  ('a1000000-0000-0000-0000-000000000004', 'Daniel Rocha Pereira', 'Daniel', 'daniel.pereira@exemplo.com', '(11) 99999-0004', 'FinanSmart', 'CEO', 'Finanças', '11-50', 'São Paulo', 'SP', '15+ anos'),
  ('a1000000-0000-0000-0000-000000000005', 'Eduarda Costa Alves', 'Edu', 'eduarda.alves@exemplo.com', '(85) 99999-0005', 'Agro Digital', 'Coordenadora de Marketing', 'Agronegócio', '51-200', 'Fortaleza', 'CE', '3-5 anos');

-- Inserir respostas de assessment de exemplo
insert into public.assessment_responses (
  student_id, strategic_moment, top_challenges, desired_results,
  ai_maturity_level, ai_maturity_score, current_ai_usage, tools_used, current_ai_use_cases, main_barriers,
  priority_area, highest_value_application, real_problem_to_use_in_course, one_ready_application_expected, application_scope,
  networking_topics, contribution_offer, desired_connections, opt_in_matchmaking,
  preferred_learning_style, participation_style, preferred_exercise_style,
  ideal_course_outcome, success_definition, post_course_application, is_complete
) values
  (
    'a1000000-0000-0000-0000-000000000001',
    'Momento de transformação digital — buscando escalar operações sem aumentar headcount proporcional',
    array['Automatizar processos repetitivos', 'Reduzir tempo de análise de dados', 'Capacitar minha equipe'],
    'Implementar pelo menos 3 soluções de IA nas operações nos próximos 6 meses',
    'intermediario', 3,
    'Uso ferramentas de IA algumas vezes por semana para análise de dados e relatórios',
    array['ChatGPT', 'Copilot', 'Power BI'],
    array['Análise de dados', 'Redação de relatórios', 'Automatização de e-mails'],
    array['Resistência cultural da equipe', 'Falta de dados estruturados'],
    'Operações e processos internos',
    'Sistema de triagem automática de solicitações internas',
    'Relatórios mensais que levam 2 dias para ser feitos manualmente',
    'Automação de relatório de KPIs operacionais',
    'Departamental — começo no meu time e expando',
    array['Gestão de operações com IA', 'Automação de processos'],
    'Experiência em implementação de projetos de transformação digital em médias empresas',
    'Conectar com outros profissionais de operações que já implementaram IA',
    true,
    'Aprender fazendo — prefiro exemplos práticos e exercícios reais',
    'Participação ativa — gosto de debater e compartilhar experiências',
    'Casos reais do meu setor adaptados ao meu contexto',
    'Sair com ao menos um processo automatizado e um roadmap claro de implementação',
    'Ter um projeto de IA em produção na minha empresa até o fim do trimestre',
    'Levar o aprendizado para minha equipe e criar um programa interno de IA',
    true
  ),
  (
    'a1000000-0000-0000-0000-000000000002',
    'Precisando aumentar conversão e personalizar a jornada de compra sem aumentar o time',
    array['Aumentar taxa de conversão', 'Personalizar atendimento ao cliente', 'Analisar dados de vendas'],
    'Aumentar conversão em 20% usando personalização com IA',
    'basico', 2,
    'Comecei a explorar IA recentemente, uso principalmente ChatGPT para textos',
    array['ChatGPT'],
    array['Criação de conteúdo', 'Respostas para clientes'],
    array['Não sei por onde começar', 'Falta de conhecimento técnico', 'Custo de implementação'],
    'Vendas e relacionamento com cliente',
    'Motor de recomendação de produtos para e-commerce',
    'Taxa de abandono de carrinho de 70% no e-commerce',
    'Sistema simples de recomendação baseado em histórico',
    'Piloto — testar em uma categoria de produto primeiro',
    array['IA para vendas', 'Personalização de experiência do cliente'],
    'Visão de varejo e comportamento do consumidor',
    'Profissionais de e-commerce e marketing digital que já usam IA',
    true,
    'Exemplos muito práticos com passo a passo detalhado',
    'Aprendo melhor observando e depois tentando',
    'Projetos guiados com suporte próximo',
    'Entender como implementar IA mesmo sem equipe técnica própria',
    'Ter uma solução de IA rodando no meu e-commerce',
    'Compartilhar com meu sócio e implementar juntos',
    true
  ),
  (
    'a1000000-0000-0000-0000-000000000003',
    'Reestruturando RH para ser mais estratégico — menos operacional, mais analítico',
    array['Automatizar processos de seleção', 'Melhorar onboarding', 'Análise preditiva de turnover'],
    'Reduzir tempo de hiring em 40% e melhorar retenção com analytics',
    'intermediario', 3,
    'Uso IA para triagem de currículos e análise de clima organizacional',
    array['ChatGPT', 'LinkedIn Recruiter AI', 'Personio'],
    array['Triagem de currículos', 'Análise de pesquisas de clima', 'Onboarding automatizado'],
    array['Integração com sistemas legados', 'LGPD e questões de privacidade'],
    'Recursos Humanos e Gestão de Pessoas',
    'Sistema preditivo de risco de turnover',
    'Alto turnover no primeiro trimestre de trabalho — custo de R$50k por reposição',
    'Dashboard de indicadores de engajamento com alertas preditivos',
    'Corporativo — implementar em toda a empresa',
    array['RH digital', 'People Analytics', 'Diversidade e inclusão com IA'],
    'Experiência em implementação de People Analytics e HRTech',
    'CHROs e gestores de pessoas usando analytics na prática',
    true,
    'Combinação de teoria e prática com discussão em grupo',
    'Gosto de compartilhar experiências e aprender com outros',
    'Exercícios que usam dados reais do meu contexto',
    'Estruturar um roadmap completo de IA para o RH da minha empresa',
    'Time de RH autônomo em uso de ferramentas de IA no dia a dia',
    'Criar um programa de IA para RH e apresentar para a diretoria',
    true
  ),
  (
    'a1000000-0000-0000-0000-000000000004',
    'Fundador buscando escalar startup de fintech com equipe enxuta',
    array['Automatizar análise de crédito', 'Melhorar detecção de fraudes', 'Personalizar produto para cada cliente'],
    'Lançar feature de IA no produto principal nos próximos 2 meses',
    'avancado', 4,
    'IA é parte central do nosso produto — usamos modelos em produção',
    array['OpenAI API', 'Python', 'AWS SageMaker', 'LangChain'],
    array['Análise de crédito automatizada', 'Detecção de anomalias', 'Personalização de produto'],
    array['Custo de API em escala', 'Latência dos modelos'],
    'Produto e desenvolvimento de negócio',
    'Agente de análise de risco em tempo real',
    'Processo manual de análise de crédito que leva 48h',
    'Reduzir análise de crédito para menos de 1 hora com IA',
    'Core do produto — afeta todos os clientes',
    array['AI para fintech', 'Regulatório e compliance com IA', 'Fundraising para startups de IA'],
    'Experiência técnica em implementação de ML em produção',
    'Founders de fintechs e investidores em IA',
    true,
    'Casos técnicos avançados e discussão de arquitetura',
    'Questionador — gosto de ir fundo nas discussões',
    'Projetos desafiadores com liberdade para explorar',
    'Conexões estratégicas e insights para escalar produto de IA',
    'Fechar rodada seed com IA como diferencial competitivo claro',
    'Apresentar case de IA para investidores',
    true
  ),
  (
    'a1000000-0000-0000-0000-000000000005',
    'Marketing precisando ser mais orientado a dados e menos dependente de achismo',
    array['Personalizar campanhas', 'Automatizar criação de conteúdo', 'Medir ROI de marketing'],
    'Automatizar 50% das tarefas repetitivas de marketing',
    'basico', 2,
    'Uso ChatGPT para criar textos mas ainda muito manualmente',
    array['ChatGPT', 'Canva AI', 'Meta AI'],
    array['Criação de conteúdo para redes sociais', 'Textos de e-mail marketing'],
    array['Não sei integrar IA com nossas ferramentas', 'Time pequeno sem tempo para aprender'],
    'Marketing e comunicação',
    'Automação de criação e publicação de conteúdo',
    'Criar 30 posts por mês para 5 redes sociais leva 3 pessoas 2 semanas inteiras',
    'Pipeline de criação de conteúdo semi-automatizado',
    'Time de marketing — impacto imediato no trabalho diário',
    array['IA para marketing', 'Automação de conteúdo', 'Agronegócio e comunicação'],
    'Visão do setor de agronegócio e comunicação rural',
    'Profissionais de marketing digital usando IA de forma avançada',
    true,
    'Visual e prático — prefiro ver antes de fazer',
    'Observo mais e contribuo quando tenho certeza',
    'Templates prontos que posso adaptar ao meu contexto',
    'Ter um fluxo de trabalho de marketing com IA que funcione',
    'Economizar 50% do tempo atual em criação de conteúdo',
    'Treinar toda a equipe de marketing nas ferramentas',
    true
  );
